fos_rest:
    zone:
        - { path: ^/admin/* }
        - { path: ^/api/* }
    format_listener:
        rules:
            - { path: ^/api/*, priorities: [json], fallback_format: json, prefer_extension: false }
            - { path: ^/admin/*, prefer_extension: true, fallback_format: json, priorities: [json, html] }
    serializer:
        serialize_null: true
    param_fetcher_listener:  false
    allowed_methods_listener:  false
    routing_loader: false
    view:
        view_response_listener:  false
