sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/src/Module/*/Infrastructure/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/src/Module/*/Infrastructure/config/lists"

sulu_core:
    locales:
        pl: Polski
    translations:
        - pl
